set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset_status]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN W5 [get_ports clock]
set_property PACKAGE_PIN A18 [get_ports tx]
set_property PACKAGE_PIN B18 [get_ports rx]
set_property PACKAGE_PIN V17 [get_ports reset]
set_property PACKAGE_PIN U16 [get_ports reset_status]
create_clock -period 10.000 -name clock -waveform {0.000 5.000} [get_ports clock]
